Liste et fermeture des tickets
tbobm/etnawrapper pull request #15
Opened 2020-05-09 20:11 UTC by matteyeux

Salut Theo !
Suite à #11, voici une nouvelle PR pour lister et fermer les tickets.

Pour les tests de suppression et lister le contenu d'un ticket : 
```python
from etnawrapper import EtnaWrapper
wrapper = EtnaWrapper(login='', password='')

tags = ['retard', 'pedago', 'suivi']

ticket = wrapper.open_ticket(title="Retard", message="Je serais en retard", tags=tags)
ticket_id = ticket['data']['id']

print("=== created ticket ===")
print("created at : %s" % ticket['data']['created_at'])
print("closed at : %s" % ticket['data']['closed_at'])
print("ticket_id : %d" % ticket_id)

print(wrapper.get_tickets(ticket_id)['data']['messages'][0]['content'])
input()

close = wrapper.close_ticket(ticket_id)
ticket_id = close['data']['id']
print("=== closed ticket ===")
print("created at : %s" % close['data']['created_at'])
print("closed at : %s" % close['data']['closed_at'])
print("ticket_id : %d" % ticket_id)
```

output
```
=== created ticket ===
created at : 2020-05-09 21:56:07
closed at : None
ticket_id : 173999
Je serais en retard

=== closed ticket ===
created at : 2020-05-09 21:56:07
closed at : 2020-05-09 22:03:44
ticket_id : 173999
```

En gros ça créé le ticket, on liste le contenu du ticket et il est supprimé ensuite.

2020-05-13 08:36 UTC, tbobm commented
Hello !

J'ai jete un coup d'oeil au code, j'ai l'impression que la `CLOSE_TICKET_URL` et `TICKET_URL` sont les memes, c'est voulu ?

Sinon LGTM, thanks! :+1:

2020-05-13 09:15 UTC, matteyeux commented
C'est du au fait que j'ai [changé](https://github.com/tbobm/etnawrapper/pull/15/commits/88991d2bc168148ffe681d93dc7a723d1cde49da#diff-37440b547b3848231ebc18be669326f3R28) la valeur de `TICKET_URL` et j'ai pas vu qu'elle était identique à `CLOSE_TICKET_URL` . C'est modifié :)

Huh, j'ai oublié un mot dans mon message de commit : *`same value`

2020-05-20 07:26 UTC, tbobm requested changes
All good du coup, mais, sauf si tu penses que c'est justifie (ca demande a modifier la doc pour expliciter le comportement en cas d'absence de `ticket_id`), je privilegie deux methodes pour un `get_single` et `get_multiple` sur ce coup :)

2020-05-20 07:26 UTC, tbobm commented on etnawrapper/etna.py
> +        return result
```suggestion
    def get_tickets(self):
        """Fetch the list of tickets."""
        url = TICKETS_URL
        result = self._query(url)
        return result
    
    
    def get_ticket(self, ticket_id: int):
        """Fetch the ticket matching `ticket_id`."""
        url = TICKET_URL.format(task_id=ticket_id)
        result = self._query(url)
        return result
```
Ca me semble plus explicite, si ca te convient :)

2020-05-21 18:01 UTC, matteyeux commented
C'était uniquement pour avoir moins de code, ton option conviens aussi et est plus lisible ^^

2020-05-25 13:22 UTC, tbobm approved these changes
Parfait ! :)

2020-05-25 13:22 UTC, merged