liste des modules d'après une date
tbobm/etnawrapper pull request #16
Opened 2020-05-11 10:33 UTC by matteyeux

Hello, 
nouvelle PR pour lister les modules d'après une date donnée. C'est ce qu'utilise le form du temps de travail pour lister les modules sur lesquels on a le droit de déclarer.

Voici ce que ça donne avec la date du 11/05
```
>>> from etnawrapper import EtnaWrapper
>>> w = EtnaWrapper(login='', password='')
>>> projects = w.get_projects(date='2020-05-11')
>>> for i,_ in enumerate(projects):
...     print(projects[i]['date_end'])
... 
2020-10-16 17:00:00
2020-05-22 23:42:00
2020-10-04 23:42:00
2020-11-06 23:42:00
2021-10-08 17:00:00
2022-12-31 23:42:00
2020-05-22 23:42:00
2020-09-18 23:42:00
2021-10-08 17:00:00
```

2020-05-13 08:41 UTC, tbobm commented
Hello !

Hm, j'ai l'impression qu'il y a un petit conflit entre le code de la PR et ton exemple, `date` semble etre un `datetime` et tu utilises un `str` dans ton exemple.

Deux options:
- soit les deux types sont valides et il faut "juste" format les calls avec des `datetime` (via `.date()` par exemple)
- soit (ma preference), on reste du du datetime avec formating

2020-05-13 09:35 UTC, matteyeux commented
Le code en question a pas retourné d'erreur sur le type de variable que je lui ai passé, du coup je n'y ai pas prêté attention.

Si je comprends bien en quoi consiste la deuxième option, il faut formater en amont ce qu'on passe à la fonction ? Comme ceci : 
```python
>>> from datetime import datetime
>>> date_str = "2020-05-11"
>>> datetime_obj = datetime.strptime(date_str, '%Y-%m-%d')
>>> projects = w.get_projects(date=datetime_obj)
```

2020-05-20 07:36 UTC, tbobm requested changes
J'ai mis bien plus de temps que prevu pour te repondre, j'ai pas trop l'occasion de me poser sur de l'open source ces derniers temps, hesite pas a me nudge si je traine trop :wink:

2020-05-20 07:36 UTC, tbobm commented on etnawrapper/etna.py
>          result = self._query(url)
Tu peux utiliser l'argument `params` de `Etnawrapper._query` :)

```suggestion
        params = dict()
        if date is not None:
            _date = date.strftime('%Y-%m-%d')
            params["date"] = _date
        result = self._query(url, params=params)
```

Je te code ca de tete, normalement ca traduit mieux ce a quoi je pensais.

Implicitement, si je dev et que j'ai un argument `date`, je m'attend soit a:
- pouvoir passer un type `datetime`
- pouvoir passer une string de date RFC8601-compliant

Si ca te convient comme approche, c'est parti :)

2020-05-21 18:26 UTC, matteyeux commented on etnawrapper/etna.py
>          result = self._query(url)
Ok je comprends mieux, tout est ok !

2020-05-25 13:06 UTC, merged

2020-05-25 13:22 UTC, tbobm commented
Nickel, thanks :)